### ISSUE TITLE
Potentially incorrect Header file

### ISSUE THREAD

**Issue by NicholasLangley** [UCSolarCarTeam/Epsilon-Desktop-Client-Telemetry#2]
src/ViewLayer/TelemetryDisplayUi/TelemetryDisplayUi.cpp line 3

**Comment by bill-luu** [comment]
`#include "ui_TelemetryDisplayUi.h"`
`ui_TelemetryDisplayUi.h` is actually generated by qmake and is the result of the UIC reading the `TelemetryDisplayUi.ui` file and generating the appropriate headers.

http://doc.qt.io/qt-4.8/uic.html#uic
